# Scroll left/right arrows for exactly 2 seconds
RIGHT seek  2 exact
LEFT  seek -2 exact

# Copy the text of the current subtitles to the clipboard by pressing Ctrl+C
# Ctrl+c set clipboard "${sub-text}"
# Ctrl+с set clipboard "${sub-text}"  # (Здесь русская буква "с")

# ========================================================
# ENGLISH LAYOUT (EN)
# ========================================================
a sub-seek -1
d sub-seek  1
s cycle sub-visibility
j cycle secondary-sid
y cycle-values secondary-sub-pos 10 90
c script-binding toggle-drum-mode
S screenshot

# =========================================================
# RUSSIAN LAYOUT (RU)
# =========================================================
ф sub-seek -1
в sub-seek  1
ы cycle sub-visibility
о cycle secondary-sid
н cycle-values secondary-sub-pos 10 90
с script-binding toggle-drum-mode
Ы screenshot

# =========================================================
# SYSTEM KEYS (work everywhere)
# ========================================================
TAB script-binding osc/visibility

# Support for Russian keys З (P) and Л (K) for the autopause.lua script
# З script-binding toggle-autopause
# Л script-binding toggle-karaoke-mode