# Display subtitles on top
sub-align-y=top
sub-margin-y=20

# Support for HTML tags and styles
sub-ass=yes
# sub-ass-override=no

save-position-on-quit=yes

# Always open the window exactly in the center of the screen
# geometry=50%:50%

# Limit the maximum window size to 80% of the screen size,
# so that the video never goes beyond the borders of the monitor
# autofit-larger=80%x80%
 
# (Optional) If you want the player to ALWAYS open in a specific size, 
# ignoring video resolution (e.g. 1280x720):
# autofit=1280x720
autofit=1920x1080

# Unbind subtitles from the window borders (now they are attached only to the video itself)
sub-scale-with-window=no
sub-ass-scale-with-window=no

# Increase or decrease the base font size from the subtitle file
# 1.0 - original size, 1.5 - 50% larger, 0.8 - 20% smaller
# sub-scale=1.5