[fields]
Quotation
WordSource
WordSource2
WordSourceInflectedForm
WordSourceInflectedForm2
WordDestination
WordDestinationInflectedForm
WordSourceContext
SentenceSourceContextLeft
SentenceSource
SentenceSourceContextRight
SentenceDestinationContextLeft
SentenceDestination
SentenceDestinationContextRight
SentenceDestination2ContextLeft
SentenceDestination2
SentenceDestination2ContextRight
SentenceSourceWordlist
SentenceSourceCloze
SentenceSourceRewriteAISentenceSource
SentenceSourceRewriteAISentenceDestination
WordSourceMorphologyAI
Note
WordRussian
WordUkrainian
WordEnglish
WordGerman
WordSourceMorphemeFirst
WordSourceMorphemeFirstDefinition
WordSourceMorphemeSecond
WordSourceMorphemeSecondDefinition
WordSourceMorphemeThird
WordSourceMorphemeThirdDefinition
WordSourceMorphemeFourth
WordSourceMorphemeFourthDefinition
WordSourceMorphemeFifth
WordSourceMorphemeFifthDefinition
WordSourceIPA
WordSourceSynonymAI
WordSourceDefinitionAISentenceSource
WordSourceDefinitionAISentenceDestination
WordSourceDefinitionFirst
WordSourceDefinitionFirstClipping
WordSourceDefinitionSecond
WordDestinationDefinitionFirst
WordDestinationDefinitionSecond
WordSourceAudio
SentenceSourceIPA
SentenceSourceAudio
Image
WordSourceCloze
WordSourceContextAI
TextSource
TextDestination
TextSourceURL
SentenceEnglish
SentenceGerman
SentenceUkrainian
SentenceRussian
Source
SourceURL
SeparatorAudio
Source-en-GB
Source-en-US
Source-de-DE
Source-uk-UA
Source-ru-RU
Destination-en-GB
Destination-en-US
Destination-de-DE
Destination-uk-UA
Destination-ru-RU
Overlapping
ToggleAlwaysEmptyField
Note ID
am-all-morphs
am-all-morphs-count
am-unknown-morphs
am-unknown-morphs-count
am-highlighted
am-score
am-score-terms
am-study-morphs
SentenceSourceIndex
Deck

; [mapping]
; Quotation=source_word
; WordSource=source_word
; WordSourceInflectedForm=source_word
; WordSourceInflectedForm2=source_word
; SentenceSource=source_sentence
; Note=time
; Deck=deck_name

[tts]
Source-en-GB=tts_source_en
Source-en-US=tts_source_us
Source-de-DE=tts_source_de
Source-uk-UA=tts_source_uk
Source-ru-RU=tts_source_ru
Destination-en-GB=tts_dest_en
Destination-en-US=tts_dest_us
Destination-de-DE=tts_dest_de
Destination-uk-UA=tts_dest_uk
Destination-ru-RU=tts_dest_ru
; Destination-ru-RU="1"

[fields_mapping.word]
; Unified field name and data source for isolated words
Quotation=source_word
WordSource=source_word
WordSourceInflectedForm=source_word
WordSourceInflectedForm2=source_word
SentenceSource=source_sentence
Note=time
Deck=deck_name

[fields_mapping.sentence]
; Unified field name and data source for sentences
SentenceSource=source_sentence
Note=time
SourceURL=Source
Deck=deck_name

[settings]
; Number of words required to switch from word to sentence mapping
sentence_word_threshold=3