-- ============================================================================
-- config.lua — Kardenwort Options table
-- ============================================================================

local M = {}

M.Options = {
    -- AutoPause
    autopause_default = true,
    karaoke_every_word = false,
    pause_padding = 0.15,
    karaoke_token = "{\\c}",
    space_tap_delay = 0.2,

    -- Drum Mode
    drum_font_size = 34,
    drum_font_name = "Consolas",
    drum_font_bold = false,
    drum_context_lines = 3,
    drum_context_opacity = "30",
    drum_context_color = "CCCCCC",
    drum_context_bold = false,
    drum_context_size_mul = 1.0,
    drum_active_opacity = "00",
    drum_active_color = "FFFFFF",
    drum_active_bold = false,
    drum_active_size_mul = 1.0,
    drum_line_height_mul = 0.87,
    drum_bg_color = "000000",
    drum_bg_opacity = "60",
    drum_border_size = 1.5,
    drum_shadow_offset = 1.0,
    drum_double_gap = true,
    drum_vsp = 0,
    drum_block_gap_mul = -0.27,
    drum_gap_adj = 6,
    drum_track_gap = 5.0,
    drum_scrolloff = 0,
    drum_pri_highlight_color = "00CCFF",
    drum_sec_highlight_color = "00CCFF",
    drum_pri_ctrl_select_color = "FF88FF",
    drum_sec_ctrl_select_color = "FF88FF",
    drum_pri_highlight_bold = false,
    drum_sec_highlight_bold = false,
    -- Interactivity Toggles (Per-Screen, Per-Mode)
    osd_interactivity = true,
    dw_pri_interactivity = true,
    dw_sec_interactivity = true,
    drum_pri_interactivity = true,
    drum_sec_interactivity = true,
    srt_pri_interactivity = true,
    srt_sec_interactivity = true,

    -- Highlighting Toggles (Per-Screen, Per-Mode)
    dw_pri_highlighting = true,
    dw_sec_highlighting = true,
    drum_pri_highlighting = true,
    drum_sec_highlighting = true,
    srt_pri_highlighting = true,
    srt_sec_highlighting = true,

    -- SRT Style (Regular Mode)
    srt_font_size = 34,
    srt_font_name = "Consolas",
    srt_font_bold = false,
    srt_active_color = "FFFFFF",
    srt_context_color = "CCCCCC",
    srt_active_opacity = "00",
    srt_context_opacity = "30",
    srt_bg_color = "000000",
    srt_bg_opacity = "60",
    srt_border_size = 1.5,
    srt_shadow_offset = 1.0,
    srt_double_gap = true,
    srt_vsp = 0,
    srt_block_gap_mul = -0.27,
    srt_line_height_mul = 0.87,
    srt_pri_highlight_color = "00CCFF",
    srt_sec_highlight_color = "00CCFF",
    srt_pri_ctrl_select_color = "FF88FF",
    srt_sec_ctrl_select_color = "FF88FF",
    srt_pri_highlight_bold = false,
    srt_sec_highlight_bold = false,

    -- Copy Mode
    copy_default_mode = "A",
    copy_filter_russian = true,
    copy_context_lines = 2,
    copy_word_limit = 3,
    copy_osd_cooldown = 3.0,
    key_copy_popup = "Shift+C",
    key_copy_main = "Alt+c",

    -- Toggle Positions
    sec_pos_top = 10,
    -- Warning: Ensure a 5% gap between sec_pos_bottom and sub-pos/sub_pos
    sec_pos_bottom = 90,

    -- System
    tick_rate = 0.05,
    osd_duration = 0.5,
    win_clipboard_retries = 5,
    win_clipboard_retry_delay = 50,
    gd_trigger_enabled = "no",
    gd_hotkey_popup = "Ctrl+Alt+Shift+Q",
    gd_hotkey_main = "Ctrl+Alt+Shift+1",
    tts_trigger_enabled = "no",
    tts_hotkey_1 = "Ctrl+Alt+Shift+1",
    tts_hotkey_2 = "Ctrl+Alt+Shift+2",
    tts_hotkey_3 = "Ctrl+Alt+Shift+3",
    tts_hotkey_4 = "Ctrl+Alt+Shift+4",
    tts_hotkey_5 = "Ctrl+Alt+Shift+5",
    tts_hotkey_6 = "Ctrl+Alt+Shift+6",
    tts_hotkey_7 = "Ctrl+Alt+Shift+7",
    tts_hotkey_8 = "Ctrl+Alt+Shift+8",
    key_tts_1 = "",
    key_tts_2 = "",
    key_tts_3 = "",
    key_tts_4 = "",
    key_tts_5 = "",
    key_tts_6 = "",
    key_tts_7 = "",
    key_tts_8 = "",
    gd_trigger_method = "powershell",
    python_path = "python",
    python_trigger_delay_popup = 0.1,
    python_trigger_delay_main = 0.5,
    gd_trigger_lock_duration = 2.0,

    -- Drum Window
    dw_font_size = 34,
    dw_key_copy = "Ctrl+c Ctrl+с",
    dw_lines_visible = 15,
    dw_scrolloff = 3,
    dw_bg_color = "000000",
    dw_bg_opacity = "60",
    dw_context_color = "CCCCCC",
    dw_active_color = "FFFFFF",
    dw_active_bold = false,
    dw_context_bold = false,
    dw_active_opacity = "00",
    dw_context_opacity = "30",
    dw_active_size_mul = 1.0,
    dw_context_size_mul = 1.0,
    dw_highlight_color = "00CCFF",
    dw_ctrl_select_color = "FF88FF",
    dw_highlight_bold = false,
    dw_font_name = "Consolas",
    dw_char_width = 0.5,
    dw_line_height_mul = 0.87,
    dw_wrap_line_height_mul = 1.05,
    dw_block_gap_mul = -0.27,
    dw_double_gap = true,
    dw_vsp = 0,
    dw_edge_margin = 24,
    dw_border_size = 1.5,
    dw_shadow_offset = 1.0,
    dw_original_spacing = true,
    dw_jump_words = 5,
    dw_jump_lines = 5,

    -- Search HUD Styling
    search_font_name = "Consolas",
    search_font_size = 34,
    search_results_font_size = 0,
    search_bg_color = "000000",
    search_bg_opacity = "60",
    search_text_color = "CCCCCC",
    search_border_size = 1.5,
    search_shadow_offset = 1.0,
    search_line_height_mul = 1.2,
    search_hit_color = "0088FF",
    search_hit_bold = false,
    search_sel_color = "FFFFFF",
    search_sel_bold = false,
    search_query_hit_color = "0088FF",
    search_query_hit_bold = false,

    -- Font Scaling (Ported from fixed_font.lua)
    font_scaling_enabled = true,
    font_base_height = 1080,
    font_base_scale = 1.0,
    font_scale_strength = 0.5,

    -- Tooltip Style (Unified Schema)
    tooltip_font_size = 34,
    tooltip_font_name = "Consolas",
    tooltip_font_bold = false,
    tooltip_context_lines = 3,
    tooltip_active_color = "FFFFFF",
    tooltip_context_color = "CCCCCC",
    tooltip_active_opacity = "00",
    tooltip_context_opacity = "30",
    tooltip_bg_color = "000000",
    tooltip_bg_alpha = "",
    tooltip_bg_opacity = "60",
    tooltip_dw_bg_alpha = "",
    tooltip_dm_bg_alpha = "FF",
    tooltip_srt_bg_alpha = "FF",
    tooltip_border_size = 1.2,
    tooltip_shadow_offset = 1.0,
    tooltip_top_pad_extra = 10,
    tooltip_line_height_mul = 0.87,
    tooltip_block_gap_mul = -0.27,
    tooltip_double_gap = true,
    tooltip_vsp = 0,
    tooltip_y_offset_lines = 0,
    tooltip_highlight_color = "00CCFF",
    tooltip_ctrl_select_color = "FF88FF",
    tooltip_active_bold = false,
    tooltip_context_bold = false,
    tooltip_highlight_bold = false,
    tooltip_native_box_policy = "auto",

    -- Navigation Repeat
    seek_hold_delay = 0.5,
    seek_hold_rate = 10,

    -- Anki Highlighter
    dw_key_add = "g MBTN_MID Ctrl+MBTN_MID",
    dw_key_pair = "f Ctrl+MBTN_LEFT",
    dw_key_select = "MBTN_LEFT",
    dw_key_pair_mod = "Ctrl",
    dw_key_tooltip_pin = "MBTN_RIGHT",
    dw_key_tooltip_hover = "n",
    dw_key_tooltip_toggle = "e",
    dw_key_seek_prev = "a",
    dw_key_seek_next = "d",
    dw_key_search = "Ctrl+f",

    dw_key_seek = "ENTER KP_ENTER",
    dw_key_replay = "s",
    dw_key_esc = "ESC",
    dw_clear_selection_after_transition = true,
    dw_key_select_extend = "Shift+MBTN_LEFT",
    dw_key_mouse_seek = "MBTN_LEFT_DBL",
    dw_key_jump_left = "Ctrl+LEFT",
    dw_key_jump_right = "Ctrl+RIGHT",
    dw_key_jump_select_left = "Ctrl+Shift+LEFT",
    dw_key_jump_select_right = "Ctrl+Shift+RIGHT",
    dw_key_scroll_up = "Ctrl+UP",
    dw_key_scroll_down = "Ctrl+DOWN",
    dw_esc_mode = "auto_follow_current",
    dw_esc_policy = "",
    dw_neutral_cursor_source = "",
    dw_key_jump_select_up = "Ctrl+Shift+UP",
    dw_key_jump_select_down = "Ctrl+Shift+DOWN",
    dw_key_select_left = "Shift+LEFT",
    dw_key_select_right = "Shift+RIGHT",
    dw_key_select_up = "Shift+UP",
    dw_key_select_down = "Shift+DOWN",
    dw_key_cycle_esc_mode = "n",
    dw_key_cycle_copy_mode = "z я",
    dw_key_toggle_copy_context = "x ч",
    -- Search Mode (Drum Window)
    search_key_bs = "BS",
    search_key_del = "DEL",
    search_key_select_left = "Shift+LEFT",
    search_key_select_right = "Shift+RIGHT",
    search_key_jump_left = "Ctrl+LEFT",
    search_key_jump_right = "Ctrl+RIGHT",
    search_key_home = "HOME",
    search_key_end = "END",
    search_key_enter = "ENTER",
    search_key_esc = "ESC",
    search_key_paste = "Ctrl+v",
    search_key_select_all = "Ctrl+a",
    search_key_delete_word = "Ctrl+w",
    search_key_click = "MBTN_LEFT",
    dw_key_open_record = "o",
    key_sub_pos_up = "r",
    key_sub_pos_down = "t",
    key_sec_sub_pos_up = "R",
    key_sec_sub_pos_down = "T",

    anki_context_max_words = 40,
    anki_context_words_before = 0,
    anki_context_words_after = 0,
    anki_context_span_pad = 3,
    anki_highlight_depth_1 = "0075D1",
    anki_highlight_depth_2 = "005DAE",
    anki_highlight_depth_3 = "003C88",
    anki_split_depth_1 = "FF88B0",
    anki_split_depth_2 = "D10069",
    anki_split_depth_3 = "A30052",
    anki_mix_depth_1 = "4A4AD3",
    anki_mix_depth_2 = "3636A8",
    anki_mix_depth_3 = "151578",
    anki_global_highlight = false,
    anki_record_file = "",
    log_level = "info",
    anki_sync_period = 5,
    anki_context_lines = 6,
    anki_local_fuzzy_window = 10.0,
    anki_split_search_window = 35,
    anki_split_gap_limit = 60.0,
    anki_neighbor_window = 5,
    anki_context_strict = false,
    anki_highlight_bold = false,
    anki_strip_metadata = true,
    unescape_tags = "\\N \\n \\h",
    anki_abbrev_list = "ca. z.B. usw. bzw. etc. t.con d.h. u.a. vgl. ggf. bspw. u.U. i.d.R. bzgl. evtl.",
    anki_abbrev_smart = true,
    anki_sentence_terminators = ".!?",
    book_mode = false,

    -- Record File
    record_editor = "C:\\Program Files\\Microsoft VS Code\\Code.exe",

    -- Colors
    dw_split_select_color = "FF88B0",
    dw_mouse_shield_ms = 50,
    dw_mouse_drag_threshold_px = 5,
    dw_mouse_auto_scroll_interval = 0.05,
    dw_mouse_edge_scroll_ratio = 0.15,
    sentence_word_threshold = 3,
    replay_ms = 2000,
    replay_count = 2,
    replay_autostop = true,
    audio_padding_start = 1000,
    audio_padding_end = 1000,
    nav_cooldown = 0.2,
    nav_tolerance = 0.05,
    autopause_overshoot = 0.1,
    key_cycle_immersion_mode = "O Щ",
    immersion_mode_default = "PHRASE",
    seek_time_delta = 2,
    seek_osd_duration = 2.0,
    seek_osd_layer = 5,
    notice_osd_layer = 5,
    seek_font_size = 60,
    seek_font_name = "Consolas",
    seek_font_bold = false,
    seek_color = "FFFFFF",
    seek_bg_color = "000000",
    seek_bg_opacity = "60",
    seek_border_size = 1.5,
    seek_shadow_offset = 1.0,
    seek_show_accumulator = true,
    seek_msg_format = "%p%v",
    seek_msg_cumulative_format = "%P%V",
    replay_msg_format = "Replay: %mms%x",
    replay_on_msg_format = "Replaying segment: %mms%x",

    -- Help HUD Styling
    help_font_name = "Consolas",
    help_font_size = 34,
    help_bg_color = "000000",
    help_bg_opacity = "60",
    help_title_color = "00CCFF",
    help_text_color = "CCCCCC",
    help_key_color = "00CCFF",
    help_column_width = 40,
    audio_switch_threshold = 1.0,
    sub_switch_threshold = 1.0,
    companion_audio_enabled = true,
    companion_audio_attach_on_load = true,
    companion_video_enabled = true,
    companion_video_attach_on_load = true,
    companion_subtitle_enabled = true,
    companion_subtitle_attach_on_load = true,
    quiz_integration = false,
    quiz_pipe_path = [[\\.\pipe\kardenwort-quiz]],
    quiz_script_path = "",
    lua_path = "lua",
}

function M.validate_config(opts, diagnostic, is_valid_key_fn)
    opts.anki_context_words_before =
        math.max(0, math.floor(tonumber(opts.anki_context_words_before) or 0))
    opts.anki_context_words_after =
        math.max(0, math.floor(tonumber(opts.anki_context_words_after) or 0))
    local errors = {}
    local function check_keys(opt_val, opt_name)
        if not opt_val or opt_val == "" then
            return
        end
        for key in opt_val:gmatch("[^%s,;]+") do
            if not is_valid_key_fn(key) then
                table.insert(
                    errors,
                    string.format(
                        "Invalid key name in '%s': '%s' (multicharacter non-ASCII names are not supported).",
                        opt_name,
                        key
                    )
                )
            end
        end
    end

    local key_opts = {
        "dw_key_add",
        "dw_key_pair",
        "dw_key_select",
        "dw_key_seek_prev",
        "dw_key_seek_next",
        "dw_key_search",
        "dw_key_copy",
        "dw_key_seek",
        "dw_key_esc",
        "dw_key_jump_left",
        "dw_key_jump_right",
        "dw_key_jump_select_left",
        "dw_key_jump_select_right",
        "dw_key_scroll_up",
        "dw_key_scroll_down",
        "dw_key_jump_select_up",
        "dw_key_jump_select_down",
        "dw_key_select_left",
        "dw_key_select_right",
        "dw_key_select_up",
        "dw_key_select_down",
        "dw_key_open_record",
        "dw_key_cycle_copy_mode",
        "dw_key_toggle_copy_context",
        "dw_key_tooltip_pin",
        "dw_key_tooltip_hover",
        "dw_key_tooltip_toggle",
        "key_sub_pos_up",
        "key_sub_pos_down",
        "key_sec_sub_pos_up",
        "key_sec_sub_pos_down",
    }

    for _, opt in ipairs(key_opts) do
        check_keys(opts[opt], "kardenwort-" .. opt)
    end

    if #errors > 0 then
        local summary = "CONFIGURATION HEALTH CHECK FAILED:\n"
        for _, err in ipairs(errors) do
            summary = summary .. "  - " .. err .. "\n"
        end
        summary = summary .. "Please correct these in your mpv.conf to avoid unexpected behavior."
        diagnostic.warn(summary, "startup-health-check")
    end
end

return M
